### ISSUE TITLE
Requesting to add contacts through your application

### ISSUE THREAD

**Issue by chithramanikalimuthu** [Shridharks/Learning_for_study#3]
Dear Shridhar,
Your application is good but whenever your adding contacts you need to save first in your mobile then only shows in whatsapp but if you are adding this features application gets more useable.

**Comment by Shridharks** [comment]
Dear Chitra,
Thanks you for suggestion.

**Comment by Shridharks** [comment]
Dear chitra,

Thanks you fr ur suggestion. new features added.
